FROM stashapp/stash as stash

# Final Runnable Image
FROM nvidia/cuda:12.0.1-base-ubuntu22.04

COPY --from=stashapp/stash /usr/bin/stash /usr/bin/
# NVENC Patch
RUN mkdir -p \
        /usr/local/bin \
        /patched-lib && \
    wget -O /usr/local/bin/patch.sh \
        https://raw.githubusercontent.com/keylase/nvidia-patch/master/patch.sh && \
    wget -O /usr/local/bin/docker-entrypoint.sh \
        https://raw.githubusercontent.com/keylase/nvidia-patch/master/docker-entrypoint.sh && \
    chmod +x \
        /usr/local/bin/patch.sh \
        /usr/local/bin/docker-entrypoint.sh \
        /usr/bin/stash

RUN apt update && \
    apt upgrade -y && \
    apt install -y \
        ca-certificates \
        libvips-tools \
        ffmpeg wget \
        i965-va-driver-shaders \
        vainfo \
        python3-pip && \
    rm -rf /var/lib/apt/lists/*

# pip packages
RUN pip3 install \
    requests \
    bs4 \
    lxml \
    pystashlib \
    stashapp-tools && \
    ln -s /usr/bin/python3 /usr/bin/python

ENV LANG C.UTF-8
ENV NVIDIA_VISIBLE_DEVICES all
ENV NVIDIA_DRIVER_CAPABILITIES=video,utility
ENV STASH_CONFIG_FILE=/root/.stash/config.yml
EXPOSE 9999
ENTRYPOINT ["docker-entrypoint.sh", "stash"]